# Data-X Spring 2019: Homework 06 

## Name : Tirth Patel
## SID : 3034227694
## Course (IEOR 135/290) : IEOR 290

### Machine Learning



In this homework, you will do some exercises with prediction. We will cover these algorithms in class, but this is for you to have some hands on with these in scikit-learn. You can refer - https://github.com/ikhlaqsidhu/data-x/blob/master/05a-tools-predicition-titanic/titanic.ipynb

Display all your outputs.


In [1]:
import numpy as np
import pandas as pd

In [2]:
 # machine learning libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier



__ 1. Read __`diabetesdata.csv`__ file into a pandas dataframe. 
About the data: __

1. __TimesPregnant__: Number of times pregnant 
2. __glucoseLevel__: Plasma glucose concentration a 2 hours in an oral glucose tolerance test 
3. __BP__: Diastolic blood pressure (mm Hg)  
5. __insulin__: 2-Hour serum insulin (mu U/ml) 
6. __BMI__: Body mass index (weight in kg/(height in m)^2) 
7. __pedigree__: Diabetes pedigree function 
8. __Age__: Age (years) 
9. __IsDiabetic__: 0 if not diabetic or 1 if diabetic) 








In [3]:
#Read data & print the head
diabetesdata = pd.read_csv('diabetesdata.csv')
diabetesdata.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic
0              6         148.0  72        0  33.6     0.627  50.0           1
1              1           NaN  66        0  26.6     0.351  31.0           0
2              8         183.0  64        0  23.3     0.672   NaN           1
3              1           NaN  66       94  28.1     0.167  21.0           0
4              0         137.0  40      168  43.1     2.288  33.0           1

**2. Calculate the percentage of Null values in each column and display it. **

In [4]:
columns = diabetesdata.columns
NullsPerColumn = diabetesdata[columns].isna().sum()*100/len(diabetesdata[columns])
print(NullsPerColumn)

TimesPregnant    0.000000
glucoseLevel     4.427083
BP               0.000000
insulin          0.000000
BMI              0.000000
Pedigree         0.000000
Age              4.296875
IsDiabetic       0.000000
dtype: float64


**3. Split __`data`__  into  __`train_df`__ and __`test_df`__  with 15% as test.**


In [6]:
#split values
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(diabetesdata, test_size = 0.15)

**4. Display the means of the features in train and test sets. Replace the null values in  __`train_df`__ and __`test_df`__  with the mean of EACH feature column separately for train and test. Display head of the dataframes.**

In [14]:
#Display the means of the features in train and test sets.
train_mean = train_df.mean()
test_mean = test_df.mean()
print(train_mean)
print(test_mean)

#Replace the null values in  train_df and test_df with the mean of EACH feature column separately for train and test.
train_df = train_df.fillna(train_mean)
test_df = test_df.fillna(test_mean)

#Display head of train dataset.
train_df.head()

TimesPregnant      3.851227
glucoseLevel     120.947200
BP                68.693252
insulin           78.602761
BMI               31.932209
Pedigree           0.466897
Age               33.112000
IsDiabetic         0.345092
dtype: float64
TimesPregnant      3.810345
glucoseLevel     121.412844
BP                71.422414
insulin           86.525862
BMI               32.331897
Pedigree           0.499862
Age               34.727273
IsDiabetic         0.370690
dtype: float64


TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
73               4         129.0  86      270  35.1     0.231  23.0   
78               0         131.0   0        0  43.2     0.270  26.0   
666              4         145.0  82        0  32.5     0.235  70.0   
360              5         189.0  64      325  31.2     0.583  29.0   
355              9         165.0  88        0  30.4     0.302  49.0   

     IsDiabetic  
73            0  
78            1  
666           1  
360           1  
355           1

In [15]:
#Diaplay head of test dataset.
test_df.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
150              1    136.000000  74      204  37.4     0.399  24.0   
9                8    121.412844  96        0   0.0     0.232  54.0   
274             13    106.000000  70        0  34.2     0.251  52.0   
206              8    196.000000  76      280  37.5     0.605  57.0   
359              1    196.000000  76      249  36.5     0.875  29.0   

     IsDiabetic  
150           0  
9             1  
274           0  
206           1  
359           1

**5. Split __`train_df`__ & __`test_df`__   into  __`X_train`__, __`Y_train`__  and __`X_test`__, __`Y_test`__. __`Y_train`__  and __`Y_test`__ should only have the column we are trying to predict,  __`IsDiabetic`__.**

In [16]:
X_train = train_df.drop('IsDiabetic', 1)
Y_train = train_df['IsDiabetic']
X_test  = test_df.drop('IsDiabetic', 1)
Y_test = test_df['IsDiabetic']

**6. Use this dataset to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies. Try different hyperparameter values for these models and see if you can improve your accuracies.**

In [17]:
# 6a. Logistic Regression - 1st iteration
from sklearn.metrics import accuracy_score, confusion_matrix
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
logreg_train_acc = accuracy_score(logreg.predict(X_train), Y_train)
logreg_test_acc = accuracy_score(logreg.predict(X_test), Y_test)
print ('logreg training acuracy= ',logreg_train_acc)
print('logreg test accuracy= ',logreg_test_acc)

logreg training acuracy=  0.7914110429447853
logreg test accuracy=  0.7327586206896551


/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [23]:
# 6a. Logistic Regression - 2nd iteration
from sklearn.metrics import accuracy_score, confusion_matrix
logreg = LogisticRegression(C = 10)
logreg.fit(X_train, Y_train)
logreg_train_acc = accuracy_score(logreg.predict(X_train), Y_train)
logreg_test_acc = accuracy_score(logreg.predict(X_test), Y_test)
print ('logreg training acuracy= ',logreg_train_acc)
print('logreg test accuracy= ',logreg_test_acc)

logreg training acuracy=  0.7883435582822086
logreg test accuracy=  0.7327586206896551


/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [18]:
# 6b. Perceptron - 1st iteration
perceptron = Perceptron()
perceptron.fit(X_train, Y_train)
perceptron_train_acc = accuracy_score(perceptron.predict(X_train), Y_train)
perceptron_test_acc = accuracy_score(perceptron.predict(X_test), Y_test )
print ('perceptron training acuracy= ',perceptron_train_acc)
print('perceptron test accuracy= ',perceptron_test_acc)

perceptron training acuracy=  0.6503067484662577
perceptron test accuracy=  0.6293103448275862


/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [25]:
# 6b. Perceptron - 2nd iteration
perceptron = Perceptron(alpha = 0.01)
perceptron.fit(X_train, Y_train)
perceptron_train_acc = accuracy_score(perceptron.predict(X_train), Y_train)
perceptron_test_acc = accuracy_score(perceptron.predict(X_test), Y_test )
print ('perceptron training acuracy= ',perceptron_train_acc)
print('perceptron test accuracy= ',perceptron_test_acc)

perceptron training acuracy=  0.6503067484662577
perceptron test accuracy=  0.6293103448275862


/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [28]:
# 6c. Random Forest - 1st iteration
random_forest = RandomForestClassifier()
random_forest.fit(X_train, Y_train)
random_forest_train_acc = accuracy_score(random_forest.predict(X_train), Y_train)
random_forest_test_acc =accuracy_score(random_forest.predict(X_test), Y_test)
print('random_forest training acuracy= ',random_forest_train_acc)
print('random_forest test accuracy= ',random_forest_test_acc)

random_forest training acuracy=  0.9815950920245399
random_forest test accuracy=  0.7241379310344828


/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [29]:
# 6c. Random Forest - 2nd iteration
random_forest = RandomForestClassifier(n_estimators = 100)
random_forest.fit(X_train, Y_train)
random_forest_train_acc = accuracy_score(random_forest.predict(X_train), Y_train)
random_forest_test_acc =accuracy_score(random_forest.predict(X_test), Y_test)
print('random_forest training acuracy= ',random_forest_train_acc)
print('random_forest test accuracy= ',random_forest_test_acc)

random_forest training acuracy=  1.0
random_forest test accuracy=  0.6982758620689655


**7. For your logistic regression model - **

**a . Compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your train set and display it. Also display the predicted class for those samples from your logistic regression model trained before. **


In [34]:
logpredicts = logreg.predict_log_proba(X_train[:10])
print(logpredicts)
predicts = logreg.predict(X_train[:10])
print(predicts)

[[-0.28188021 -1.40390471]
 [-1.48590649 -0.25656735]
 [-0.66228123 -0.72499626]
 [-1.76183208 -0.18841603]
 [-1.19995434 -0.3584021 ]
 [-0.0309234  -3.49166404]
 [-0.28503231 -1.39428603]
 [-0.28240011 -1.40230973]
 [-1.29329549 -0.32070832]
 [-0.21853807 -1.62807494]]
[0 1 0 1 1 0 0 0 1 0]


**b . Now compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your test set and display it. Also display the predicted class for those samples from your logistic regression model trained before.
 (using the model trained on the training set)**


In [35]:
logpredicts = logreg.predict_log_proba(X_test[:10])
print(logpredicts)
predicts = logreg.predict(X_test[:10])
print(predicts)

[[-0.4708078  -0.9794904 ]
 [-0.0168921  -4.08934336]
 [-0.62318912 -0.76837   ]
 [-2.93773234 -0.05444113]
 [-2.18126063 -0.11979657]
 [-0.18625488 -1.77232162]
 [-0.23403906 -1.56700558]
 [-0.32515793 -1.28162181]
 [-0.71015936 -0.67641958]
 [-0.04028611 -3.23182385]]
[0 0 0 1 1 0 0 0 1 0]


**c . What can you interpret from the log probabilities and the predicted classes?**



A greater absolute value of log probability in a certain class indicates that the sample will belong to that class.

**8. Is mean imputation is the best type of imputation (as we did in 4.) to use? Why or why not? What are some other ways to impute the data?**

No, mean imputation is not the best way as it does not take into account the values of other columns for the same row. All missing values are being replaced with mean, which seems to be a lot of generalization, and is not accommodating to outliers.

One can instead choose some other column as y, treat our column as x and train a model to fit x to y. Then fill the missing values of x with whatever is predicted by the model.

## Extra Credit (2 pts) - MANDATORY for students enrolled in IEOR 290


**9.  Implement the K-Nearest Neighbours (https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm) algorithm for k=1 from scratch in python (do not use KNN from existing libraries). KNN uses Euclidean distance to find nearest neighbors. Split your dataset into test and train as before. Also fill in the null values with mean of features as done earlier. Use this algorithm to predict values for 'IsDiabetic' for your test set. Display your accuracy. **

In [36]:
X_train_array = X_train.values
Y_train_array = Y_train.values# convert dataframe to numpy array
X_test_array = X_test.values
Y_test_array = Y_test.values

preds = []
for i in range(X_test_array.shape[0]):
    sample = X_test_array[i]
    distances = X_train_array@sample# array of distances for a vector in test set to each of the vectors in training set

    minidx = np.argmin(distances)# Y label in training set corresponding to the minimum distance 
    preds.append(Y_train_array[minidx])
    
print("Predictions - ", preds)
preds = np.array(preds)
differences = np.abs(preds - Y_test_array)
accuracy = (len(differences)-np.sum(differences))/len(differences)
print("Accuracy - ", accuracy)

Predictions -  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Accuracy -  0.6293103448275862
